# Global project configuration

label_studio:
  project_id: 3

video_processing:
  frame_stride: 12          # Annotate every 12 frames
  mot_fps: 2                # 24 / 12
  use_original_resolution: true
  default_width: 1920
  default_height: 960

mot:
  output_dir: "data/mot_output"

exports:
  export_dir: "data/exports"
  split_dir: "data/exports/split"

videos:
  directory: "videos"
